CAS-14086
casangi/casabench pull request #18
Opened 2023-05-03 17:55 UTC by amcnicho

Add a new test file that adapts some subset of test_stk_alma_pipeline_imaging.py to casabench

- [x] test_standard_cube_eph_briggsbwtaper (iter0 only)
- [x] test_standard_cube_eph_briggsbwtaper_restart (iter0 + iter1)
- [ ] test_mosaic_cube_briggsbwtaper
- [ ] test_mosaic_cube_eph_briggsbwtaper
- [ ] test_mosaic_mfs
- [ ] test_mosaic_mtmfs
- [ ] test_mosaic_mfs_eph
- [ ] test_mosaic_mtmfs_eph
- [ ] test_standard_cube_briggsbwtaper
- [ ] test_standard_mfs
- [ ] test_standard_mfs_eph
- [ ] test_standard_mtmfs
- [ ] test_standard_mtmfs_eph

2023-05-03 17:58 UTC, amcnicho commented
The iteration control parameters are set per-test as currently implemented on this branch. Repeating each new test only once to try and minimize wall time, it still took 22.3±0m for `bench_alma.BaseMosaic.time_mosaic_cube_eph_pcwdT` and 1.35±0h (!) for `bench_alma.BaseMosaic.time_mosaic_cube_eph_pcwdT_restart` to finish on my development machine. Most of the other test cases should take far shorter...

2023-05-04 12:51 UTC, smcastro commented
I think the list you added in your first comment doesn't show the two tests you added. You added those referring to the original test_mosaic_cube_eph_pcwdT, isn't that right?
It is a lot to have the restart running in more than an hour. But it might be correct. In my SSD disk it took about 28 minutes. I don't like much the idea of repeating the tests to do the diff because it is a lot of repetition. I think we should only have a single test case with both tclean commands for iter0 and iter1 together and monitor the joint time.

2023-07-11 13:49 UTC, smcastro requested changes

2023-07-17 14:10 UTC, smcastro approved these changes

2023-07-24 13:34 UTC, merged